services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    environment:
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
    volumes:
      - ./app:/app
