services:
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - 3380:6379/tcp
    volumes:
      - ./services/redis/data:/data:rw
    environment:
      REDIS_ARGS: "--appendonly yes"

  agent_1:
    image: python:latest
    build:
      context: services/agent
      dockerfile: Dockerfile
    environment:
      - AGENT_ID=1
    volumes:
      - ./services/agent/app:/app:r
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: sh -c "sleep 5 && python3 /app/run.py --execresults --fromindex 1 --toindex 28 && sleep infinity"

  agent_2:
    image: python:latest
    environment:
      - AGENT_ID=2
    build:
      context: services/agent
      dockerfile: Dockerfile
    volumes:
      - ./services/agent/app:/app:r
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: sh -c "sleep 5 && python3 /app/run.py --execurls --fromindex 28 --toindex 29 && sleep infinity"
    depends_on:
      - redis

  agent_3:
    image: python:latest
    environment:
      - AGENT_ID=3
    build:
      context: services/agent
      dockerfile: Dockerfile
    volumes:
      - ./services/agent/app:/app:r
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: sh -c "sleep 5 && python3 /app/run.py --execdomainsqueries --fromindex 29 --toindex 30 && sleep infinity"
    depends_on:
      - redis

  client1:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_1/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3010
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3010:3000
      - 3011:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client2:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_2/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3020
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3020:3000
      - 3021:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client3:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_3/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3030
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3030:3000
      - 3031:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client4:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_4/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3040
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3040:3000
      - 3041:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client5:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_5/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3050
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3050:3000
      - 3051:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client6:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_6/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3060
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3060:3000
      - 3061:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client7:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_7/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3070
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3070:3000
      - 3071:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client8:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_8/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3080
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3080:3000
      - 3081:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client9:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_9/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3090
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3090:3000
      - 3091:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client10:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_10/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3100
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3100:3000
      - 3101:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client11:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_11/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3110
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3110:3000
      - 3111:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client12:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_12/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3120
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3120:3000
      - 3121:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client13:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_13/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3130
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3130:3000
      - 3131:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client14:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_14/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3140
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3140:3000
      - 3141:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client15:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_15/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3150
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3150:3000
      - 3151:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client16:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_16/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3160
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3160:3000
      - 3161:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client17:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_17/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3170
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3170:3000
      - 3171:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client18:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_18/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3180
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3180:3000
      - 3181:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client19:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_19/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3190
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3190:3000
      - 3191:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client20:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_20/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3200
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3200:3000
      - 3201:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client21:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_21/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3210
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3210:3000
      - 3211:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client22:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_22/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3220
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3220:3000
      - 3221:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client23:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_23/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3230
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3230:3000
      - 3231:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client24:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_24/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3240
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3240:3000
      - 3241:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client25:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_25/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3250
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3250:3000
      - 3251:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client26:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_26/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3260
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3260:3000
      - 3261:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client27:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_27/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3270
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3270:3000
      - 3271:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client28:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_28/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3280
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3280:3000
      - 3281:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client29:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_29/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3290
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3290:3000
      - 3291:3001
    shm_size: "1gb" #optional
    restart: unless-stopped

  client30:
    image: googlebot-client:1.0.3
    security_opt:
      - seccomp:unconfined #optional
    entrypoint: [/init]
    volumes:
      - ./services/client/app:/app:r
      - ./logs:/logs
      - ./services/client/volumes/client_30/.cache:/config/.cache
    environment:
      - CLIENT_PORT=3300
      - PUID=5001
      - PGID=5001
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3300:3000
      - 3301:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
