services:
  redis:
    ports:
      - :6379

  client1:
    ports:
      - :3000
      - :3001
  client2:
    ports:
      - :3000
      - :3001
  client3:
    ports:
      - :3000
      - :3001
  client4:
    ports:
      - :3000
      - :3001
  client5:
    ports:
      - :3000
      - :3001
  client6:
    ports:
      - :3000
      - :3001
  client7:
    ports:
      - :3000
      - :3001
  client8:
    ports:
      - :3000
      - :3001
  client9:
    ports:
      - :3000
      - :3001
  client10:
    ports:
      - :3000
      - :3001
